version : '3.7'
services:
  notif:
    env_file: .env
    build: .
    command: python manage.py run
    ports:
    - ${GRPC_PORT}:5000
    networks:
    - kong-net
networks:
  kong-net:
    external: true
