version : '3.7'
services:
        notif_grpc:
                env_file: .env
                build: .
                command: python manage.py run
                ports:
                - ${GRPC_PORT}:5001
