# Generated by Django 3.0.5 on 2020-04-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200426_0341"),
    ]

    operations = [
        migrations.DeleteModel(name="Shop",),
    ]
